name: example
description: This app demonstrates the capabilities of navigation_history_observer and shows the typical use case for it.

publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  navigation_history_observer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
